### ISSUE TITLE
Create a MySQL database engine

### ISSUE THREAD

**Issue by nicolasmelo1** [nicolasmelo1/PyQuery#1]
### Create a new database engine for MySQL.

Right now the user can only use the Potgres engine, it would be nice to use a MySQL engine so the users can have the same functionality they have with postgres but with MySQL.

For Postgres we use the psycopg2 python library that is easy to work with, it needs to find a mysql python library that returns the results the same way as psycopg2 for MySQL.

### How to
Engines are created [this way](https://github.com/nicolasmelo1/PyQuery/blob/master/query/engine.py). You just need to follow along with the postgres engine and export the same methods.

**Comment by domielias** [comment]
Hi, i'm interesting in participate in this commit. How can i talk to you?

**Comment by nicolasmelo1** [comment]
Hello @domielias. You can find me on discord or telegram with the @nicolasmelo1 nickname if you wish to talk to me personally
