### ISSUE TITLE
Create a SQLIte dabase engine

### ISSUE THREAD

**Issue by nicolasmelo1** [nicolasmelo1/PyQuery#2]
### Create a new database engine for SQLIte.

Right now the user can only use the Potgres engine, it would be nice to use a SQLIte engine so the users can have the same functionality they have with postgres but with SQLIte.

For Postgres we use the psycopg2 python library that is easy to work with, it needs to find a SQLIte python library that returns the results the same way as psycopg2 but for SQLIte.
How to

### How to

Engines are created [this way](https://github.com/nicolasmelo1/PyQuery/blob/master/query/engine.py). You just need to follow along with the postgres engine and export the same methods.

**Comment by chavarera** [comment]
with the help of sqlalchemy we can create sqlite engine

**Comment by nicolasmelo1** [comment]
@chavarera I think there is no point in using sqlalchemy for this project. Sqlalchemy in its own is a querybuilder actually. A really robust querybuilder. People that will be using this will be probably trying to avoid sqlachemy in any way. Also sqlachemy in its own is a huge dependency just for an engine. We can always create our own connector for sqlite, but i think it is easier to use it with a third party library.

**Comment by nicolasmelo1** [comment]
@chavarera python offers this https://docs.python.org/3/library/sqlite3.html

**Comment by chavarera** [comment]
@nicolasmelo1 ok
